name: restaurant_app
description: "A submission Dicoding project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.10.4

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  dio: ^5.9.1
  go_router: ^17.0.1
  equatable: ^2.0.8
  logger: ^2.6.2
  get_it: ^9.2.0
  chucker_flutter: ^1.9.1
  cached_network_image: ^3.4.1
  flutter_svg: ^2.2.3
  skeleton_text: ^3.0.1
  flutter_rating_bar: ^4.0.1
  lottie: ^3.3.2
  intl: ^0.20.2
  provider: ^6.1.5+1
  shared_preferences: ^2.5.4
  flutter_local_notifications: ^20.0.0
  sqflite: ^2.4.2
  path: ^1.9.1
  uuid: ^4.5.2
  workmanager: ^0.9.0+3
  rxdart: ^0.28.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  mockito:
  build_runner:

flutter:
  uses-material-design: true

  assets:
    - assets/lotties/
    - assets/images/
    - assets/icons/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/poppins/poppins_light.ttf
          weight: 300
        - asset: assets/fonts/poppins/poppins_regular.ttf
          weight: 400
        - asset: assets/fonts/poppins/poppins_italic.ttf
          style: italic
          weight: 400
        - asset: assets/fonts/poppins/poppins_medium.ttf
          weight: 500
        - asset: assets/fonts/poppins/poppins_semibold.ttf
          weight: 600
        - asset: assets/fonts/poppins/poppins_bold.ttf
          weight: 700
